- hdt-fuseki/pom.xml
- hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java
- hdt-java-core/pom.xml
Hello,
I cloned your library this morning and when I tried to build it, I noticed several issues with Maven dependencies in **hdt-jena-core** and **hdt-fuseki**. So, here is the fixes I propose to correct them.
The issues were the following :
The Maven reference for **hdt-java-parent** in the *pom.xml* file was using the wrong version number (1.1.1-SNAPSHOT instead of 2.0). I fix it by putting the correct number.
@bendiken open a pull request #8 to add a missing dependency to jena-fuseki for it, which correspond to the v2 of fuseki. But **hdt-fuseki** seems to use the fuseki v1, so I change the dependency to jena-fuseki1 14.0. This was the source of the issue #10 .
There was also an issue with the imports in *FusekiHDTCmd.java*. Most of the imported package were incorrect, since the …
> Fix Maven dependencies issues with hdt-jena-core and hdt-fuseki

- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/DictionarySectionCache.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/DictionarySectionCachePerThread.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/LRUCache.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/ByteBufferInputStream.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/CompactString.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ReplazableString.java
squid:S1161 - "@Override" annotation should be used on any method overriding.
https://dev.eclipse.org/sonar/rules/show/squid:S1161
Faisal Hameed
> Code quality fix - "@Override" annotation should be used on any method overriding.

- hdt-java-core/hdt.cfg
- hdt-java-core/pom.xml
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64Jarray.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/DictionaryFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/FourSectionDictionaryBig.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/PFCDictionarySectionBig.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/example/ExampleGenerate.java
@luda171 updated java-hdt  to be able to process bigger files with 64 bit address space.
The problems with java-hdt were related to the fact that java's native array types use 32-bit int for length and indexing.
This means the maximum length of each array is   (2 power of 31 -1) ~ 2 billion elements.  
Also other java classes like ByteArrayOutputStream etc depend on arrays in the internal implementation, so they are fast becoming out of capacity.
All changes are in the hdt-java-core .
The patch  consists  of update of PFCDictionarySectionBig.java where I implemented  2 missed methods : load and save. I used the same array of array approach here as in the other methods already was present in this class.. 
Also I  added  SequenceLog64Jarray.java  where I ported code from  SequenceLog64.java …
> added array of arrays implementation of dictionary

- hdt-api/src/main/java/org/rdfhdt/hdt/dictionary/DictionaryUtil.java
- hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVocabulary.java
- hdt-api/src/main/java/org/rdfhdt/hdt/header/HeaderUtil.java
- hdt-api/src/main/java/org/rdfhdt/hdt/util/UnicodeEscape.java
- hdt-java-cli/src/main/java/org/rdfhdt/hdt/tools/HDTVerify.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/BitmapFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/integer/VByte.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/DictionaryFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/DictionarySectionFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/HDTFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/iterator/utils/Iter.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/RDFParserFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/TriplesFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/TripleOrderConvert.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/BitUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/ProfilingUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/RDFInfo.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/StringUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/IOUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/listener/ListenerUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ByteStringUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/UnicodeEscape.java
- hdt-jena/src/main/java/org/apache/jena/graph/JenaNodeCreator.java
- hdt-jena/src/main/java/org/rdfhdt/hdtjena/HDTJenaConstants.java
- hdt-jena/src/main/java/org/rdfhdt/hdtjena/solver/OptimizedCount.java
squid:S1118 - Utility classes should not have public constructors.
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Faisal Hameed
> Code quality fix - Utility classes should not have public constructors.

- hdt-api/src/main/java/org/rdfhdt/hdt/dictionary/Dictionary.java
- hdt-api/src/main/java/org/rdfhdt/hdt/dictionary/DictionarySection.java
- hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDT.java
- hdt-api/src/main/java/org/rdfhdt/hdt/listener/ProgressListener.java
- hdt-api/src/main/java/org/rdfhdt/hdt/options/ControlInfo.java
- hdt-api/src/main/java/org/rdfhdt/hdt/options/HDTOptions.java
- hdt-api/src/main/java/org/rdfhdt/hdt/rdf/RDFAccess.java
- hdt-api/src/main/java/org/rdfhdt/hdt/rdf/RDFParserCallback.java
- hdt-api/src/main/java/org/rdfhdt/hdt/triples/IteratorTripleID.java
- hdt-api/src/main/java/org/rdfhdt/hdt/triples/IteratorTripleString.java
- hdt-api/src/main/java/org/rdfhdt/hdt/triples/Triples.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/ModifiableBitmap.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/DynamicSequence.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/Sequence.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/DictionaryPrivate.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/DictionarySectionPrivate.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/TempDictionary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/TempDictionarySection.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/HDTPrivate.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/TempHDT.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/iterator/utils/MergedIterator.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/iterator/utils/Reducer.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/TempTriples.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/TriplesPrivate.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/PredicateIndex.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/crc/CRC.java
- hdt-jena/src/main/java/org/rdfhdt/hdtjena/cache/DictionaryCache.java
- hdt-jena/src/main/java/org/rdfhdt/hdtjena/solver/HDTSolverLib.java
- hdt-jena/src/main/java/org/rdfhdt/hdtjena/util/Abortable.java
squid:S2333 - Redundant modifiers should not be used.
https://dev.eclipse.org/sonar/rules/show/squid:S2333
Faisal Hameed
> Code quality fix - Redundant modifiers should not be used.

- hdt-api/src/main/java/org/rdfhdt/hdt/util/UnicodeEscape.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap375.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap64.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/ProfilingUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/crc/CRC16.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/crc/CRC32.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/IOUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/CompactString.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ReplazableString.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/UnicodeEscape.java
- hdt-jena/src/main/java/org/rdfhdt/hdtjena/solver/OpExecutorHDT.java
- hdt-jena/src/main/java/org/rdfhdt/hdtjena/solver/OptimizedCount.java
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Faisal Hameed
> Code quality fix - Useless parentheses around expressions should be removed

- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/BaseDictionary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/BaseTempDictionary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/DictionarySectionFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/iterator/RoleIteratorTripleID.java
squid:SwitchLastCaseIsDefaultCheck - "switch" statements should end with a "default" clause. 
https://dev.eclipse.org/sonar/rules/show/squid:SwitchLastCaseIsDefaultCheck
Faisal Hameed
> Code quality fix - "switch" statements should end with a "default" clause.

- hdt-api/src/main/java/org/rdfhdt/hdt/triples/TripleID.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/ProfilingUtil.java
squid:S2131- Primitives should not be boxed just for "String" conversion.
https://dev.eclipse.org/sonar/rules/show/squid:S2131
Faisal Hameed
> Code quality fix - Primitives should not be boxed just for "String" conversion.

- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/DeflateIntegerIterator.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceInt32.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64.java
squid:S1319 - Declarations should use Java collection interfaces such as "List" rather than specific implementation.
https://dev.eclipse.org/sonar/rules/show/squid:S1319
Faisal Hameed
> Code quality fix - Declarations should use Java collection interfaces such as "List" rather than specific implementation.

- hdt-jena/src/main/java/org/rdfhdt/hdtjena/cmd/HDTSparql.java
I wanted to perform a CONSTRUCT query against a HDT file but found that the hdtsparql command line tool only supports SELECT queries. I extended it to support CONSTRUCT, DESCRIBE and ASK queries as well.
This is very simplistic as the output formats are hardwired (N-Triples for CONSTRUCT/DESCRIBE, and a simple true/false string for ASK). It would be ideal to add a command line option for selecting the output format, but that is beyond the scope of this PR.
> Support CONSTRUCT/DESCRIBE/ASK in hdtsparql command line tool

- hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVocabulary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/HDTImpl.java
**Issue: HDT files produced by the current master cannot be read by other HDT libraries, nor an earlier version of this library, and unnecessarily so.**
Starting with 1e62eb178e503c717e53aa45a38bf3114cd5d3b9, HDT files were being written with a format IRI of `http://purl.org/HDT/hdt#HDTv1-1-2`. This unnecessarily breaks compatibility with existing HDT libraries, which expect the version URL to be `http://purl.org/HDT/hdt#HDTv1`. Since the version number indicates `HDT_version.index_version.release`, only the first component matters to the HDT file itself. This commit reverts the version IRI to `http://purl.org/HDT/hdt#HDTv1`, restoring backward compatibility with other HDT libraries. It also reverts the version detection code to simple equality.
Partially reverts …
> HDT format identifier uses only HDT version.

- hdt-java-package/bin/hdtsparql.sh
- hdt-jena/bin/hdtsparql.sh
- hdt-jena/src/main/java/org/rdfhdt/hdtjena/cmd/HDTSparql.java
This PR implements #42 i.e. adds a `-stream` option to the `hdtsparql` command line tool which causes it to return CONSTRUCT and DESCRIBE query results in a streaming fashion, as they are generated by the query engine. There is an attempt to suppress duplicate triples using a 1000-slot cache to check for already emitted triples, but of course, some duplicate triples may still occur in the output.
> Add streaming option to hdtsparql for CONSTRUCT and DESCRIBE queries (#42)

- hdt-jena/src/main/java/org/rdfhdt/hdtjena/HDTGraphAssembler.java
To make the assembler compatible with jena-spatial, it must be initialized during class loading.
> HDTGraphAssembler : add static initialization

- hdt-java-cli/src/main/java/org/rdfhdt/hdt/tools/HDT2RDF.java
This PR fixes the order of parameters in the usage message and makes it obvious that the output file is always in N-Triples format.
> Fix hdt2rdf usage message. Fixes #38

- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ReplazableString.java
See issue #36 for a description of the problem that this PR fixes.
> Fix invalid cast that breaks lookup of non-ASCII literals. Fixes #36

- hdt-jena/src/main/java/org/rdfhdt/hdtjena/solver/HDTSolverLib.java
hdtjena seems to have problems with handling nodes that have been bound to variables in SPARQL using BIND or VALUES, but don't actually exist within the HDT dictionary. This is an attempt at fixing the problem, but I'm not at all sure that it's the correct approach. It seems to fix the particular issue I had (#37) but there may be side effects such as NPEs in other code paths. The unit tests that do exist seem to pass though.
> Proposed fix for problem with handling nodes that don't exist in HDT in bindings.

- .gitignore
- hdt-api/pom.xml
- hdt-fuseki/pom.xml
- hdt-java-cli/pom.xml
- hdt-java-core/pom.xml
- hdt-java-package/pom.xml
- hdt-jena/pom.xml
- pom.xml
Maven best practice is to specify dependency versions in the parent pom to help ensure all modules use the same versions of dependencies.
Also, performed a little Maven cleanup, including the following:
* Changed the project version from `2.0` to `2.0-SNAPSHOT`.  Although `2.1-SNAPSHOT` might be a better choice.
* Changed the JUnit dependency scope from `compile` to `test`.
* `hdt-java-core` no longer depends on JCommander.
* Updated `maven-compiler-plugin` config to reflect the fact that `hdt-java-core` requires Java 7 to compile and all Jena code requires Java 8 to compile.  I did not move `hdt-api` and `hdt-java-core` up to Java 8 yet to avoid possibly breaking `hdt-mr` w/old versions of Hadoop.
> Move Maven dependency version specs into parent pom

- README.md
- hdt-api/src/main/java/org/rdfhdt/hdt/triples/TripleString.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/AdjacencyList.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap375.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapTriplesIterator.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/SortUtils.java
Speed-up the read line by moving from the regexp based _replaceAll_ to charsequence matching _replace_
On the Freebase dump, I noticed a gain between 10 and 15% depending on the machine.
> Speeding up line parsing

- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64Map.java
hdtCat fails currenlty for very large files due to a int overflow. this is fixed here
> bug when using hdtCat for very large files

- hdt-fuseki/pom.xml
When I take the current repository and try to compile, this fails for the fuseky module. This is fixe with this pull request
> Fix a problem preventing the problem to compile

- hdt-java-cli/bin/rdf2hdtcat.sh
- hdt-java-package/bin/hdtCat.sh
- hdt-java-package/bin/hdtVerify.sh
- hdt-java-package/bin/rdf2hdtcat.sh
Now that the `hdtCat` has been merged, several tools that can be found in `hdt-java-cil/bin` are missing in `hdt-java-package/bin`:
* hdtCat.sh
* hdtVerify.sh
* rdf2hdtcat.sh
This means that when compiling with `mvn assembly:single` they will be missing from the distribution directory.
Additionally, I fixed some typos and changed rdf2hdtcat.sh to assume that other tools are in `$PATH`
> Copy missing tools from hdt-java-cli to hdt-java-package

- hdt-api/src/main/java/org/rdfhdt/hdt/util/UnicodeEscape.java
This is a small issue building on my development laptop which uses java 15 for building.
> Fix to allow building on JDK11+. Javadoc tag <tt> replaced with <code>

- hdt-api/src/main/java/org/rdfhdt/hdt/triples/TripleString.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/DelayedString.java
This PR fixes TripleString equality (using equals) being sometimes by value and sometimes by reference. The issue was observed when comparing a `List<TripleString>` produced from an `HDT.search()` call against a list of expected values in a unit test of another project.
Since there was a `TripleString.equals(TripleString)` method, I figured the intention was to have equality by value and not equality by reference. This PR makes equality by value consistent. All tests pass, but if the intention was to have only equality by reference, maybe `TripleString.equals(TripleString)` should be renamed (or removed since it is not called).
Changes:
- `TripleString` now overrides Object.equals(Object) instead of overloading. Thus `left.equals(right)` works even if at compile time `left` is an Object …
> Always compare TripleString and DelayedString by value

- hdt-jena/src/main/java/org/rdfhdt/hdtjena/NodeDictionary.java
I was running into the issue that triples that could not be joined produced the following:
```
java.lang.NullPointerException: null
at org.rdfhdt.hdt.dictionary.impl.BaseDictionary.getSection(BaseDictionary.java:192) ~[hdt-java-core-2.1.3-SNAPSHOT.jar:?]
at org.rdfhdt.hdt.dictionary.impl.BaseDictionary.idToString(BaseDictionary.java:217) ~[hdt-java-core-2.1.3-SNAPSHOT.jar:?]
at org.rdfhdt.hdtjena.NodeDictionary.translate(NodeDictionary.java:217) ~[hdt-jena-2.1.3-SNAPSHOT.jar:?]
at org.rdfhdt.hdtjena.solver.StageMatchTripleID.translateBinding(StageMatchTripleID.java:185) ~[hdt-jena-2.1.3-SNAPSHOT.jar:?]
```
My assumption was that this these were `"Does not exist" ids` as documented in `org.rdfhdt.hdtjena.bindings.HDTId`. This patch fixes this issue.
> Catch 'does not exist Id' case in translate

- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap375.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/HDTImpl.java
We are introducing a major improvement in creating the extra predicates index where the major fix is in the Bitmap375 that basically represents the bitmaps of the triples. There is an operation which is select1(long n) which finds the position where (n) ones have appeared up to that position, and the idea behind this operation is to get the number of distinct sub trees in the forest of the SPO (i.e get the position of the parent) as arranged in the figure below:
And this operation in its core uses a binary search to look over the array of longs representing the bits in the bitmap, and find the block where the (n) number of bits has been set to 1.
We first removed the SortUtils binary search because there was a bug with bigger indexes, and we noticed that the search is stopping on the …
> Performance improvement in creating the extra index

- hdt-api/src/main/java/org/rdfhdt/hdt/dictionary/Dictionary.java
- hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVersion.java
- hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVocabulary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/DictionaryFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/BaseDictionary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/DictionaryPFCOptimizedExtractor.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/HashDictionary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/MultDictionaryPFCOptimizedExtractor.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/MultipleBaseDictionary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/MultipleSectionDictionary.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/MultipleSectionDictionaryBig.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/OptimizedExtractor.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/HashDictionarySection.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/HDTImpl.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/iterator/DictionaryTranslateIteratorBuffer.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/CustomIterator.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/LiteralsUtils.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/CharSequenceCustomComparator.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/literalsDict/HDTLiteralsDictTest.java
We introduce a new structure of the dictionary object's section in this pull request, the model proposed is introduced and explained in the thesis of Javier D. Fernandez  attached here: [memoriaImpresion4Diciembre.pdf](https://github.com/rdfhdt/hdt-java/files/7846161/memoriaImpresion4Diciembre.pdf)
In this new implementation the main idea is to split the objects section into multiple sections per datatype (i.e integers, dates, floats, strings ...etc), and the main purpose of this approach is to be able to get information about the literals natively and almost in constant time. We can do filtering with (datatype,str,isLiteral,lang..etc) natively on the dictionary, while in the previous implementation we had to iterate through all objects in order to do filters and this can be …
> Literals dictionary - splitting objects into subsections by datatype

- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64Big.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64BigDisk.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/PFCDictionarySectionBig.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapTriples.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/PredicateIndexArray.java
We are adding some bug fixes to use longs and SeqLog64Big in order to avoid overflow problems when dealing with very large files where integers don't suffice anymore.
There is a as well some edge cases when a section is empty and using PFCSectionDictionaryBig class, it throws an exception so we handle this as well.
Some casts to int in resize methods as well are changed to just use long instead to avoid IndexOutOfBoundException when we have an overflow and get a negative value when the arrays are so big.
> Bug fixes to avoid overflow problems

- hdt-api/src/main/java/org/rdfhdt/hdt/triples/TripleString.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/triples/TripleStringTest.java
I was facing a bug where I was doing an the equals of 2 TripleString from 2 different searches, the value should have been true, but it wasn't [(This line)](https://github.com/ate47/hdt-java/blob/tripleposition-next/hdt-java-core/src/test/java/org/rdfhdt/hdt/triples/impl/utils/HDTSortedUtils.java#L65).
In the Javadoc of [CharSquence](https://docs.oracle.com/javase/8/docs/api/java/lang/CharSequence.html), we can read:
> interface does not refine the general contracts of the [equals](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-) and [hashCode](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--) methods. The result of comparing two objects that implement CharSequence is therefore, in general, undefined
So we need to check …
> Fix TripleString match and equals methods if the CharSequences don't have equals() implemented

- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/integer/VByte.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/PFCDictionarySectionMap.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/PFCOptimizedExtractor.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/BigMappedByteBuffer.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ByteStringUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ReplazableString.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/dictionary/impl/section/PFCDictionarySectionMapTest.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/util/io/BigMappedByteBufferTest.java
I've made this little fix for #126, it's using multiple MappedByteBuffer instead of one if the size of the bytebuffer is too big (the max size is set to Integer.MAX_VALUE)
Because the ByteBuffer classes constructors of the nio package are package-private, I wasn't able to create a children of the ByteBuffer class, so I cloned the methods using the ByteBuffer to use my new class, BigMappedByteBuffer.
I've tried all the methods reimplemented to see if it was working across multiple mapped buffers. So 5 new tests were added + 1 ignored because it was using the test HDT ``dbpedia2016-10.hdt``. (36GB+)
> Fix #126 "Make sure bytebuffer never exceeds Integer.MAX_VALUE"

- hdt-api/src/main/java/org/rdfhdt/hdt/rdf/RDFParserCallback.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/TempHDTImporterOnePass.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/TempHDTImporterTwoPass.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/header/PlainHeader.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserList.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserRAR.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserRIOT.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserSimple.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserTar.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserZip.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/hdt/impl/TempHDTImporterTest.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/hdt/writer/TripleWritterHDTTest.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/rdf/parsers/AbstractNTriplesParserTest.java
- hdt-java-core/src/test/resources/importer/bnode_x.nt
- hdt-java-core/src/test/resources/importer/bnode_z.nt
~~In this pull request, I've fixed the issue #158, it add a new class ``MultiPassBNodeParser `` to clear a ``RDFParserCallback.RDFCallback`` and return the same BNodes id at each parse, the bnodes names are still random, but we can now control the random seed with the HDTOptions "loader.bnode.seed" (0 = random).~~
~~It also impact the One-Pass parser, so if we set a seed, we will get the same bnode names with a Two or One pass parser, removing the randomness if needed.~~
Edit:
In this pull request, I added to the API in the RDF parser an option to ask to keep blank nodes or node while parsing, this feature is then used to fix the issue #158  with the 2-pass parsing.
> Fix "IllegalFormatException or IllegalArgumentException while reading RDF with B-Nodes in two-pass mode" #158

- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/integer/VByte.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/DictionaryCat.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/FourSectionDictionaryCat.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/FourSectionDictionaryDiff.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/MultipleSectionDictionaryCat.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/MultipleSectionDictionaryDiff.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/PFCDictionarySectionBig.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/PFCDictionarySectionMap.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/utilCat/CatUnion.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/utilCat/SectionUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/HDTImpl.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/BigByteBuffer.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ByteStringUtil.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ReplazableString.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/hdtCat/HdtCatRandomTest.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/util/LargeFakeDataSetStreamSupplier.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/util/io/BigByteBufferTest.java
In this pull request, I've fixed the issue #104, in fact in was the same issue as the issue #126, but for the HDTs obtained with ``HDTManager.loadHDT(...)``, the previous pull request #154 was fixing the bug for HDT obtained with ``HDTManager.mapHDT(...)``. My fix is the same as the one for the map.
HDT-Java was casting a long value to an int, but because the long was bigger than ``Integer.MAX_VALUE``, it was creating an overflow and returning a negative ID.
This pull request wasn't as obvious as the previous one, while searching for the bug, I've fixed some warnings and create an utility test class ``LargeFakeDataSetStreamSupplier`` to create large test HDT or RDF streams and added some int to long in the mapped section, I can rebase my commits to remove them if necessary.
> Fix #104 "java.lang.NegativeArraySizeException parsing Wikidata HDT file" and fix some warnings

- hdt-api/src/main/java/org/rdfhdt/hdt/enums/RDFNotation.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/RDFParserFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserDir.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserHDT.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/ContainerException.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/rdf/parsers/RDFParserDirTest.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/rdf/parsers/RDFParserHDTTest.java
This pull request add 2 RDF parsers, one for the directories (removing the fixme) and one for HDTs, so it's quicker to get the content of an HDT. It's using the mapHDT method to get the content.
I've added tests to test both of the parsers.
> Implement dir and hdt parser

- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/integer/VByte.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/ByteStringUtil.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/util/io/BigByteBufferTest.java
In the pull request #104, I forgot to cast to long a value, it was throwing an exception for big enough hdt, example:
```
java.lang.ArrayIndexOutOfBoundsException: Index 74 out of bounds for length 74
at org.rdfhdt.hdt.util.string.ByteStringUtil.strcmp(ByteStringUtil.java:193) ~[hdt-java-core-3.0.2.jar!/:na]
at org.rdfhdt.hdt.dictionary.impl.section.PFCDictionarySectionBig.locateBlock(PFCDictionarySectionBig.java:242) ~[hdt-java-core-3.0.2.jar!/:na]
at org.rdfhdt.hdt.dictionary.impl.section.PFCDictionarySectionBig.locate(PFCDictionarySectionBig.java:263) ~[hdt-java-core-3.0.2.jar!/:na]
at org.rdfhdt.hdt.dictionary.impl.BaseDictionary.stringToId(BaseDictionary.java:136) ~[hdt-java-core-3.0.2.jar!/:na]
```
This pull request contains the fix for this error.
> fix IndexOutOfBound for loaded HDT BigByteBuffer of size > 2^31

- hdt-api/src/main/java/org/rdfhdt/hdt/triples/TripleString.java
- hdt-api/src/main/java/org/rdfhdt/hdt/util/UnicodeEscape.java
- hdt-java-cli/src/main/java/org/rdfhdt/hdt/tools/RDF2HDT.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/HDTManagerImpl.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/TempHDTImporterOnePass.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/TempHDTImporterTwoPass.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/RDFParserFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserDir.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserList.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserRAR.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserSimple.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserTar.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserZip.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/rdf/parsers/RDFParserSimpleTest.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/util/LargeFakeDataSetStreamSupplier.java
In this pull request, I've added a argument to the RDF2HDT CLI command to use the simple NT parser ``RDFParserSimple``, it also add a option for the generateHDT command with the option
- ``parser.ntSimpleParser`` = ``true|false``
I've also optimized the algorithm to reduce the number of calls to substring to the minimum, reducing the number of string copy.
> allow using nt simple parser in RDF2HDT cli/generateHDT

- hdt-java-core/pom.xml
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap375Disk.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap64Disk.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceInt32.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceInt64.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64Big.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/HDTImpl.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapTriples.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapTriplesIteratorMapDiff.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/IOUtil.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/compact/sequence/LargeArrayTest.java
In this pull request I've updated the JLargeArrays dependency to use the [latest version](https://gitlab.com/visnow.org/JLargeArrays/-/packages/1097495) with the fix for #167. It was required to use the Gitlab development release because no Maven central version exists.
Added to that I've updated the code for the new version and replaced SequenceLog64 to SequenceLog64Big.
It should also fix #173
> Update JLargeArrays and use SequenceLog64Big instead of SequenceLog64

- hdt-java-cli/bin/hdtVerify.bat
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap375Disk.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap64Disk.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/DynamicSequence.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceInt32.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceInt64.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64Big.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64BigDisk.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/HDTFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/HDTManagerImpl.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/HDTPrivate.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/HDTImpl.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/WriteHDTImpl.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/TriplesFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/TriplesPrivate.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapTriples.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/OneReadTempTriples.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/PredicateIndex.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/PredicateIndexArray.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/TriplesList.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/TriplesListLong.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/WriteBitmapTriples.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/disk/LongArrayDisk.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/CloseMappedByteBuffer.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/IOUtil.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/triples/impl/BitmapTriplesTest.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/util/disk/LongArrayDiskTest.java
- hdt-jena/src/test/java/org/rdfhdt/hdtjena/util/GraphConverter.java
In this PR I added the hdt option `bitmaptriples.sequence.disk` (boolean) to allow to Index an HDT using the disk versions of the Sequence/Bitmap, this is an internal change to the CORE, so if the option isn't specified, nothing will change.
I've fixed a bug in the LongArrayDisk class.
I've added tests to check my changes.
> add disk HDT indexing

- .github/workflows/mvn-windows.yaml
- .github/workflows/mvn.yaml
- .github/workflows/package.yml
Hello!
This is a small pull request to add the package archive into the release when releasing a new version, I've made a demo here with [this release](https://github.com/ate47/hdt-java/releases/tag/test), we can download the rdfhdt.tar.gz file created with mvn package
The link https://github.com/rdfhdt/hdt-java/releases/latest/download/rdfhdt.tar.gz can be put in a readme
I've also updated the Java version of the CI to Java 17, but I'm packaging using Java 11 to avoid compiling issues.
> Update CI to Java 17 and add package for release

- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/disk/LongArrayDisk.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/util/disk/LongArrayDiskTest.java
There is an error in the set0 method in LongArrayDisk, this PR fix it, it was using long indexes instead of byte indexes in the file, causing some issues with the *8 added.
> Fix set0 with LongArrayDisk

- hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/kcat/KCatImpl.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/util/io/Closer.java
Fix an issue if the closer array is null
> Fix issue with closer if the diffcat isn't used but an error is thrown

- hdt-api/src/main/java/org/rdfhdt/hdt/exceptions/ParserException.java
- hdt-api/src/main/java/org/rdfhdt/hdt/quad/QuadString.java
- hdt-api/src/main/java/org/rdfhdt/hdt/triples/TripleString.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/RDFParserFactory.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/JenaNodeFormatter.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserRIOT.java
- hdt-java-core/src/main/java/org/rdfhdt/hdt/rdf/parsers/RDFParserSimple.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/rdf/parsers/RDFParserSimpleTest.java
- hdt-java-core/src/test/java/org/rdfhdt/hdt/util/LargeFakeDataSetStreamSupplier.java
Hello,
In this PR I've upgraded the canonical ntriples parser to read nquad files, I've created a QuadString class to support the context, but it can also be used with the TripleString class, but the context won't be saved. I've also added to the RIOT parser the reading of the quads.
> Add simple parser extension to parse NQuad and QuadString
